version: '2.3'
services:
  gcloud-config:
    # Containter to store credentials created by `gcloud auth`
    image: busybox
    volumes:
    - /root/.config
  gcloud:
    image: google/cloud-sdk:280.0.0-alpine
    volumes_from:
    - gcloud-config
    tty: true
    working_dir: /work
    volumes:
    - ./cloudbuild/cloudbuild.sh:/work/cloudbuild.sh
    - ./cloudbuild/cloudbuild.yaml:/work/cloudbuild.yaml
  go_sample:
    image: go_sample
    build:
      context: ./run-go
    volumes_from:
    - gcloud-config
    volumes:
    - ./run-go:/work
    tty: true
  create_comp:
    build:
      context: ./terra
    volumes_from:
      - gcloud-config
    working_dir: /work
    tty: true